// Generated by scripts/generate-runtime-prelude.mjs from runtime/prelude.ts.
// Do not edit by hand.

export function runtimePreludeSource(): string {
  return (
    "function __topaz_runtime_prelude_init(): void {\n}\n\nfunction __topaz_string_starts_with(s: string, search: string): boolean {\n  if (search.length > s.length) return false;\n  let i: number = 0;\n  while (i < search.length) {\n    if (s.charCodeAt(i) !== search.charCodeAt(i)) return false;\n    i = i + 1;\n  }\n  return true;\n}\n\nfunction __topaz_string_ends_with(s: string, search: string): boolean {\n  if (search.length > s.length) return false;\n  let offset: number = s.length - search.length;\n  let i: number = 0;\n  while (i < search.length) {\n    if (s.charCodeAt(offset + i) !== search.charCodeAt(i)) return false;\n    i = i + 1;\n  }\n  return true;\n}\n\nfunction __topaz_string_is_trim_start_code(code: number): boolean {\n  return code === 32 || code === 9 || code === 10 || code === 13 || code === 12 || code === 11;\n}\n\nfunction __topaz_string_trim_start(s: string): string {\n  let start: number = 0;\n  while (start < s.length) {\n    if (!__topaz_string_is_trim_start_code(s.charCodeAt(start))) break;\n    start = start + 1;\n  }\n  return s.slice(start);\n}\n"
  );
}
