// Generated by scripts/generate-runtime-prelude.mjs from runtime/prelude.ts.
// Do not edit by hand.

export function runtimePreludeSource(): string {
  return (
    "function __topaz_runtime_prelude_init(): void {\n}\n\nfunction __topaz_string_starts_with(s: string, search: string): boolean {\n  if (search.length > s.length) return false;\n  let i: number = 0;\n  while (i < search.length) {\n    if (s.charCodeAt(i) !== search.charCodeAt(i)) return false;\n    i = i + 1;\n  }\n  return true;\n}\n"
  );
}
