// Generated by scripts/generate-runtime-prelude.mjs from runtime/prelude.ts.
// Do not edit by hand.

export function runtimePreludeSource(): string {
  return (
    "function __topaz_runtime_prelude_init(): void {\n}\n"
  );
}
